# Generated by Django 3.2.4 on 2021-06-29 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Classificacoes',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Formas de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=60)),
                ('data_expectativa', models.DateField()),
                ('data_recebimento', models.DateField()),
                ('situacao', models.IntegerField(choices=[(0, 'A Receber'), (1, 'Recebido')])),
                ('classificacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finances_app.classificacao')),
                ('forma_pagamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finances_app.formapagamento')),
            ],
            options={
                'verbose_name_plural': 'Contas a Receber',
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=60)),
                ('data_pagamento', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('situacao', models.IntegerField(choices=[(0, 'A Pagar'), (1, 'Pago')])),
                ('classificacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finances_app.classificacao')),
                ('forma_pagamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finances_app.formapagamento')),
            ],
            options={
                'verbose_name_plural': 'Contas a Pagar',
            },
        ),
    ]
