# Generated by Django 3.2.4 on 2021-07-01 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances_app', '0002_auto_20210629_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='classificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances_app.classificacao'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances_app.formapagamento'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='classificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances_app.classificacao'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances_app.formapagamento'),
        ),
    ]
